services:
  - type: web
    name: hoover-web
    env: docker
    plan: starter # You'll likely need the 'Starter' plan for ffmpeg memory usage
    region: ohio
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: DROPCRATE_INBOX_DIR
        value: /data/inbox
    disk:
      name: hoover-storage
      mountPath: /data
      sizeGB: 10 # To persist your DJ Library downloads
